sprint №13 add controllers
Sad-Duck/java-shareit pull request #1
Opened 2023-01-11 16:29 UTC by Sad-Duck

2023-01-12 09:59 UTC, Sad-Duck commented
Прошу прощения забыл сделать проект публичным:)

2023-01-13 05:55 UTC, Frilock requested changes
Добрый день, работу посмотрел, основной комментарий - во всех классах модели отсутствуют модификаторы доступы к полям, просьба их добавить. Так же оставил ряд небольших комментариев. Жду новую версию.

2023-01-13 05:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    long id;
Отсутствуют приватные модификаторы доступа.

2023-01-13 05:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception_handler/ExceptionsHandler.java
> +
Лишняя пустая строка

2023-01-13 05:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    Long id;
Отсутствуют модификаторы, просьба добавить

2023-01-13 05:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/dto/ItemDto.java
> +    Long id;
Модификаторы

2023-01-13 05:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/impl/InMemoryItemStorage.java
> +        } else {
Вообще лишний блок else, у вас же внутри if return стоит. На мой взгляд, лучше было бы сделать - if (item == null) {
throw ...
}
....

2023-01-13 05:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/impl/InMemoryItemStorage.java
> +        if (text.isEmpty() || text.isBlank()) {
Если text == null, то NPE получите. Лучше пользоваться - StringUtils.isBlank(...); библиотека от apache common3

2023-01-13 05:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/impl/InMemoryItemStorage.java
> +        if (newItem.getName() != null) {
Данные конструкции можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-01-13 05:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +@Component
А Вам тут точно нужно делать данный класс спринговым бином? Все равно все методы статичные

2023-01-13 05:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +@Repository
Смотрите, над интерфейсами нет смысла ставить аннотации помечающих класс бином, главное чтоб аннотация стояла над реализацией данного интерфейса.

2023-01-13 05:55 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/impl/InMemoryUserStorage.java
> +        if (users.values().stream().filter(u -> u.getEmail().equals(user.getEmail())).findAny().isEmpty()) {
а email всегда заполняется? А то NPE получите. Лучше null safe equals
Objects.equals(o1, o2)

2023-01-14 06:49 UTC, Frilock approved these changes
Работу принимаю, но там в двух местах лучше поправить. В следующей итерации поправь пожалуйста

2023-01-14 06:49 UTC, Frilock commented on pom.xml
> +			<version>3.12.0</version>
Версию лучше в properties выносить

2023-01-14 06:49 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/impl/InMemoryItemStorage.java
>          if (newItem.getDescription() != null) {
Отображается как будто старый код ты тут не убрал

2023-01-19 19:29 UTC, merged